config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'gallery/index'
  resources :curator_of_exhibitions
  resources :curators
  resources :artworks
  resources :exhibitions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "gallery#index"
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  mount_uploader :cover, CoverUploader
  has_many :curator_of_exhibitions
  has_many :curators, through: :curator_of_exhibitions
  has_many :artworks
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exhibition_params
      params.require(:exhibition).permit(:name, :about, :cover)
    end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_form.html.erb
<%= form_with(model: exhibition, local: true) do |form| %>
  <% if exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
        <% exhibition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.text_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exhibitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibitions.each do |exhibition| %>
      <tr>
        <td><%= exhibition.name %></td>
        <td><%= exhibition.about %></td>
        <td><%= exhibition.cover %></td>
        <td><%= link_to 'Show', exhibition %></td>
        <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
        <td><%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibition', new_exhibition_path %>

app/views/exhibitions/new.html.erb
<h1>New Exhibition</h1>

<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Back', exhibitions_path %>

app/views/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exhibition.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @exhibition.about %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @exhibition.cover %>
</p>

<%= link_to 'Edit', edit_exhibition_path(@exhibition) %> |
<%= link_to 'Back', exhibitions_path %>