config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'gallery/index'
  resources :curator_of_exhibitions
  resources :curators
  resources :artworks
  resources :exhibitions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "gallery#index"
end

app/models/curator.rb
class Curator < ApplicationRecord
  has_many :curator_of_exhibitions
  has_many :exhibitions, through: :curator_of_exhibitions
end

app/controllers/curators_controller.rb
class CuratorsController < ApplicationController
  before_action :set_curator, only: [:show, :edit, :update, :destroy]

  # GET /curators
  # GET /curators.json
  def index
    @curators = Curator.all
  end

  # GET /curators/1
  # GET /curators/1.json
  def show
  end

  # GET /curators/new
  def new
    @curator = Curator.new
  end

  # GET /curators/1/edit
  def edit
  end

  # POST /curators
  # POST /curators.json
  def create
    @curator = Curator.new(curator_params)

    respond_to do |format|
      if @curator.save
        format.html { redirect_to @curator, notice: 'Curator was successfully created.' }
        format.json { render :show, status: :created, location: @curator }
      else
        format.html { render :new }
        format.json { render json: @curator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curators/1
  # PATCH/PUT /curators/1.json
  def update
    respond_to do |format|
      if @curator.update(curator_params)
        format.html { redirect_to @curator, notice: 'Curator was successfully updated.' }
        format.json { render :show, status: :ok, location: @curator }
      else
        format.html { render :edit }
        format.json { render json: @curator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curators/1
  # DELETE /curators/1.json
  def destroy
    @curator.destroy
    respond_to do |format|
      format.html { redirect_to curators_url, notice: 'Curator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curator
      @curator = Curator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curator_params
      params.require(:curator).permit(:name, :about, :cover)
    end
end

app/helpers/curators_helper.rb
module CuratorsHelper
end

app/views/curators/_form.html.erb
<%= form_with(model: curator, local: true) do |form| %>
  <% if curator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curator.errors.count, "error") %> prohibited this curator from being saved:</h2>

      <ul>
        <% curator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.text_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curators/edit.html.erb
<h1>Editing Curator</h1>

<%= render 'form', curator: @curator %>

<%= link_to 'Show', @curator %> |
<%= link_to 'Back', curators_path %>

app/views/curators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curators.each do |curator| %>
      <tr>
        <td><%= curator.name %></td>
        <td><%= curator.about %></td>
        <td><%= curator.cover %></td>
        <td><%= link_to 'Show', curator %></td>
        <td><%= link_to 'Edit', edit_curator_path(curator) %></td>
        <td><%= link_to 'Destroy', curator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curator', new_curator_path %>

app/views/curators/new.html.erb
<h1>New Curator</h1>

<%= render 'form', curator: @curator %>

<%= link_to 'Back', curators_path %>

app/views/curators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @curator.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @curator.about %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @curator.cover %>
</p>

<%= link_to 'Edit', edit_curator_path(@curator) %> |
<%= link_to 'Back', curators_path %>