config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'gallery/index'
  resources :curator_of_exhibitions
  resources :curators
  resources :artworks
  resources :exhibitions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "gallery#index"
end

app/models/curator_of_exhibition.rb
class CuratorOfExhibition < ApplicationRecord
  belongs_to :exhibition
  belongs_to :curator
end

app/controllers/curator_of_exhibitions_controller.rb
class CuratorOfExhibitionsController < ApplicationController
  before_action :set_curator_of_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /curator_of_exhibitions
  # GET /curator_of_exhibitions.json
  def index
    @curator_of_exhibitions = CuratorOfExhibition.all
  end

  # GET /curator_of_exhibitions/1
  # GET /curator_of_exhibitions/1.json
  def show
  end

  # GET /curator_of_exhibitions/new
  def new
    @curator_of_exhibition = CuratorOfExhibition.new
  end

  # GET /curator_of_exhibitions/1/edit
  def edit
  end

  # POST /curator_of_exhibitions
  # POST /curator_of_exhibitions.json
  def create
    @curator_of_exhibition = CuratorOfExhibition.new(curator_of_exhibition_params)

    respond_to do |format|
      if @curator_of_exhibition.save
        format.html { redirect_to @curator_of_exhibition, notice: 'Curator of exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @curator_of_exhibition }
      else
        format.html { render :new }
        format.json { render json: @curator_of_exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curator_of_exhibitions/1
  # PATCH/PUT /curator_of_exhibitions/1.json
  def update
    respond_to do |format|
      if @curator_of_exhibition.update(curator_of_exhibition_params)
        format.html { redirect_to @curator_of_exhibition, notice: 'Curator of exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @curator_of_exhibition }
      else
        format.html { render :edit }
        format.json { render json: @curator_of_exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curator_of_exhibitions/1
  # DELETE /curator_of_exhibitions/1.json
  def destroy
    @curator_of_exhibition.destroy
    respond_to do |format|
      format.html { redirect_to curator_of_exhibitions_url, notice: 'Curator of exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curator_of_exhibition
      @curator_of_exhibition = CuratorOfExhibition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curator_of_exhibition_params
      params.require(:curator_of_exhibition).permit(:name, :about, :cover)
    end
end

app/helpers/curator_of_exhibitions_helper.rb
module CuratorOfExhibitionsHelper
end

app/views/curator_of_exhibitions/_form.html.erb
<%= form_with(model: curator_of_exhibition, local: true) do |form| %>
  <% if curator_of_exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curator_of_exhibition.errors.count, "error") %> prohibited this curator_of_exhibition from being saved:</h2>

      <ul>
        <% curator_of_exhibition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.text_field :cover %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curator_of_exhibitions/edit.html.erb
<h1>Editing Curator Of Exhibition</h1>

<%= render 'form', curator_of_exhibition: @curator_of_exhibition %>

<%= link_to 'Show', @curator_of_exhibition %> |
<%= link_to 'Back', curator_of_exhibitions_path %>

app/views/curator_of_exhibitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curator Of Exhibitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curator_of_exhibitions.each do |curator_of_exhibition| %>
      <tr>
        <td><%= curator_of_exhibition.name %></td>
        <td><%= curator_of_exhibition.about %></td>
        <td><%= curator_of_exhibition.cover %></td>
        <td><%= link_to 'Show', curator_of_exhibition %></td>
        <td><%= link_to 'Edit', edit_curator_of_exhibition_path(curator_of_exhibition) %></td>
        <td><%= link_to 'Destroy', curator_of_exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curator Of Exhibition', new_curator_of_exhibition_path %>

app/views/curator_of_exhibitions/new.html.erb
<h1>New Curator Of Exhibition</h1>

<%= render 'form', curator_of_exhibition: @curator_of_exhibition %>

<%= link_to 'Back', curator_of_exhibitions_path %>

app/views/curator_of_exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @curator_of_exhibition.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @curator_of_exhibition.about %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @curator_of_exhibition.cover %>
</p>

<%= link_to 'Edit', edit_curator_of_exhibition_path(@curator_of_exhibition) %> |
<%= link_to 'Back', curator_of_exhibitions_path %>